Hummingbird.MangaLibraryEntry = DS.Model.extend
  manga: DS.belongsTo('manga')
  status: DS.attr('string')
  isFavorite: DS.attr('boolean')
  rating: DS.attr('number')
  chaptersReaded: DS.attr('number')
  volumesReaded: DS.attr('number')
  private: DS.attr('boolean')
  rereading: DS.attr('boolean')
  rereadedCount: DS.attr('number')
  lastReaded: DS.attr('date')
  
  positiveRating: (-> @get('rating') >= 3.6).property('rating')
  negativeRating: (-> @get('rating') <= 2.4).property('rating')
  neutralRating: (-> @get('rating') > 2.4 and @get('rating') < 3.6).property('rating')
