#!/bin/bash

use_node() {
  nvm install $1
  nvm use $1
  npm config set spin false
}
use_ruby() {
  rvm use $1 --binary --fuzzy --install
}

if [ $TESTGROUP = 'client' ]; then
  use_node $USE_NODE
elif [ $TESTGROUP = 'server' ]; then
  use_ruby $USE_RUBY
else
  use_node $USE_NODE
  use_ruby $USE_RUBY
fi
