#!/bin/bash

install_server_deps() {
  (
    cd server
    bundle install --deployment --jobs=3 --retry=3
  )
}

install_client_deps() {
  (
    cd client
    travis_retry npm install -g bower
    travis_retry npm install
    travis_retry bower install
  )
}

if [ $TESTGROUP = 'client' ]; then
  install_client_deps
elif [ $TESTGROUP = 'server' ]; then
  install_server_deps
else
  install_client_deps
  install_server_deps
fi
